#+title: Woof! 🐕 howto

#+html: <div class="container">

* What is Woof! and how to use it?

Woof! monitors updates sent to a mailbox and exposes them on the web.
Typically, this mailbox is subscribed to a mailing list with a public
online archive so that Woof! reports can link to it.

Woof! tries to be *a good companion for free software maintainers* who
work with mailing lists by allowing them to focus on /bugs/ and /patches/.
It also aims at *making life easier for users* by pointing at important
news such as upcoming changes.

Woof! does not change the way maintainers use a mailing list for the
development of their projects: with a minimalistic set of conventions,
Woof! will extract what's important for everyone.

* Triggering a report

Woof! watches for triggers at the beginning of the subject line:

- =[ANN]= : An annoucement
- =[BUG]= : A bug report
- =[HELP]= : A help request

It also watches for patches:

- =[PATCH]= : A single patch
- =[PATCH n/m]= : A patch in a series
- A multipart mail with a =text/x-diff= or =text/x-patch= MIME part

Some triggers are special:

- =[CHANGE x]= : Announce a change in the release =x=
- =[RELEASE x]= : Announce the release =x=

The =x= part is mandatory for changes and releases and it should not
contain any whitespace.

Announcing a release =x= moves changes for =x= from the /Upcoming changes/
section to the /Latest released changes/ one.  Canceling a release moves
the changes back to the /Upcoming changes/ section.

* Updating a report

After a bug, patch, announcement, change, release or help request has
been monitored, replies to the original mail can trigger actions.

Actions are declared at the beginning of a line in the reply.

- For *bugs*:
  - =Confirmed.= : Confirm a bug.
  - =Fix.= : Mark a bug as fixed.

- For *patches*:
  - =Approved.= : Approve a patch.
  - =Applied.= : Mark a patch as applied.

- For *help requests*:
  - =Handled.= : Mark a request as currently handled.
  - =Done.= : Mark a task of helping as done.

For bugs, patches, requests, announcements, changes and releases, you
can also cancel them:

- =Canceled=. : Mark the bug, patch, request, announcement, change or
  release as canceled.

*Note*: A punctuation mark among =;:,.= is /mandatory/ for these reports.

* Notifications

Users receive a mail notification when they triggers a Woof! report.

You can turn control notifications by writing to the Woof! mailbox
with this command at the beginning of a line:

- =Notifications: false= : To turn notifications off
- =Notifications: true= : To turn notifications on

* Admins and maintainers

Each Woof! instance comes with a default admin.

*Admins* can perform these actions:

- =Add admin: woof@woof.io=
- =Add maintainer: woof@woof.io=
- =Ban: woof@woof.io=
- =Ignore: woof@woof.io=

You can also use =Remove= instead of =Add= and =Unban= and =Unignore=:

- =Remove admin: woof@woof.io=
- =Remove maintainer: woof@woof.io=
- =Unban: woof@woof.io=
- =Unignore: woof@woof.io=

Admins can also update the configuration:

- =Maintenance: true= : Put the website in maintenance mode
- =Notifications: true= : Enable/disable mail notifications
- =Theme: my_theme= : Use =my_theme= for the interface
- =Enable: feature= : Enable a feature
- =Disable: feature= : Disable a feature

=feature= can be one of =bug=, =announcement=, =request=, =change=, =release= or
=mail= and truth values can be negated as =false=.

*Maintainers* can perform these actions:

- =Add maintainer: woof@woof.io=
- =Ban: woof@woof.io=
- =Unban: woof@woof.io=
- =Ignore: woof@woof.io=

They cannot remove admins or maintainers and they cannot unignore and
unban other contributors.

* Woof without a mailing list

Woof! can monitor a mailbox that is not subscribed to a public list.
In that case, the webpage exposes reports as texts with no links.  But
you can check reports by using their =json= export: it will give you the
=Message-Id= of each report, allowing to find the corresponding email.

#+html: </div>

