(ns bzg.config)

(def config
  {:user             (System/getenv "WOOF_MAIL_USER")
   :server           (System/getenv "WOOF_MAIL_SERVER")
   :password         (System/getenv "WOOF_MAIL_PASSWORD")
   :mailing-list     (System/getenv "WOOF_MAILING_LIST")
   :release-manager  (System/getenv "WOOF_RELEASE_MANAGER")
   :mail-url-format  (System/getenv "WOOF_MAIL_URL_FORMAT")
   :folder           (System/getenv "WOOF_MAIL_FOLDER")
   :project-name     (System/getenv "WOOF_PROJECT_NAME")
   :project-url      (System/getenv "WOOF_PROJECT_URL")
   :title            (System/getenv "WOOF_TITLE")
   :base-url         (System/getenv "WOOF_BASE_URL")
   :feed-title       (System/getenv "WOOF_FEED_TITLE")
   :feed-description (System/getenv "WOOF_FEED_DESCRIPTION")
   })
